export const PARTY_GET_PROGRESS = "PARTY_GET_PROGRESS";
export const PARTY_GET_SUCCESS = "PARTY_GET_SUCCESS";
export const PARTY_GET_ERROR = "PARTY_GET_ERROR";

export const PARTY_POST_PROGRESS = "PARTY_POST_PROGRESS";
export const PARTY_POST_SUCCESS = "PARTY_POST_SUCCESS";
export const PARTY_POST_ERROR = "PARTY_POST_ERROR";

export const PARTY_DELETE_PROGRESS = "PARTY_DELETE_PROGRESS";
export const PARTY_DELETE_SUCCESS = "PARTY_DELETE_SUCCESS";
export const PARTY_DELETE_ERROR = "PARTY_DELETE_ERROR";

export const PARTY_UPDATE_PROGRESS = "PARTY_UPDATE_PROGRESS";
export const PARTY_UPDATE_SUCCESS = "PARTY_UPDATE_SUCCESS";
export const PARTY_UPDATE_ERROR = "PARTY_UPDATE_ERROR";