export const ELECTION_GET_PROGRESS = "ELECTION_GET_PROGRESS"
export const ELECTION_GET_SUCCESS = "ELECTION_GET_SUCCESS"
export const ELECTION_GET_ERROR = "ELECTION_GET_ERROR"

export const ELECTION_POST_PROGRESS = "ELECTION_POST_PROGRESS";
export const ELECTION_POST_SUCCESS = "ELECTION_POST_SUCCESS";
export const ELECTION_POST_ERROR = "ELECTION_POST_ERROR";

export const ELECTION_DELETE_PROGRESS = "ELECTION_DELETE_PROGRESS";
export const ELECTION_DELETE_SUCCESS = "ELECTION_DELETE_SUCCESS";
export const ELECTION_DELETE_ERROR = "ELECTION_DELETE_ERROR";

export const ELECTION_UPDATE_PROGRESS = "ELECTION_UPDATE_PROGRESS";
export const ELECTION_UPDATE_SUCCESS = "ELECTION_UPDATE_SUCCESS";
export const ELECTION_UPDATE_ERROR = "ELECTION_UPDATE_ERROR";